# Generated by Django 3.2.12 on 2022-02-10 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
