# Generated by Django 3.2.12 on 2022-02-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_art_artimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='artimage',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
