# Generated by Django 3.2.12 on 2022-03-01 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_auto_20220301_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='art.project'),
        ),
    ]
