# Generated by Django 2.0.7 on 2022-08-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_alter_artimage_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='artimage',
            name='image',
            field=models.ImageField(default='default/error image.png', upload_to='art_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
