# Generated by Django 3.2.12 on 2022-02-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220216_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
    ]
