# Generated by Django 3.2.12 on 2022-03-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_about_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='instagram_username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
